linters-settings:
  govet:
    check-shadowing: true

linters:
  disable-all: true
  fast: false

  enable:
    - stylecheck    #Stylecheck is a replacement for golint
    - unconvert     #Remove unnecessary type conversions
    - errcheck      #Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - gosec         #Inspects source code for security problems
    - gocyclo       #Computes and checks the cyclomatic complexity of functions
    - gocognit      #Computes and checks the cognitive complexity of functions
    - dupl          #Tool for code clone detection
    - misspell      #Finds commonly misspelled English words in comments
    - unparam       #Reports unused function parameters
    - gosimple      #Linter for Go source code that specializes in simplifying a code
    - typecheck     #Like the front-end of a Go compiler, parses and type-checks Go code
    - ineffassign   #Detects when assignments to existing variables are not used
    - unused        #Finds unused global variables and constants
    - revive        #Fast, configurable, extensible, flexible, and beautiful linter for Go.
    - nakedret      #Finds naked returns in functions greater than a specified function length
    - prealloc      #Finds slice declarations that could potentially be preallocated
    - staticcheck   #Staticcheck is a go vet on steroids, applying a ton of static analysis checks

run:
  concurrency: 2
  tests: false

output:
  format: tab

service:
  golangci-lint-version: 1.52.x
